export function translate() {
    var translation = {
        "AUTO_BOOT": "开机启动",
        "SHUTDOWN": "关机",
        "SMS_SEND": "发送短信",
        "SMS_RECEIVE": "接收短信",
        "SMS_MODIFY": "修改短信",
        "SMS_QUERY": "查询短信",
        "SMS_DELETE": "删除短信",
        "SMS_INSERT": "插入短信",
        "HTTPGET": "get方式",
        "HTTPPOST": "post方式",
        "CREATE_URL": "创建url",
        "OPEN_CONNECTION": "打开连接",
        "ENCODE_URL": "对URL编码",
        "GET_SOCKET": "获取socket",
        "GET_SERVER_SOCKET": "获取serverSocket",
        "CREATE_SOCKET": "创建socket",
        "BIND": "绑定socket",
        "CRYPUPDATE": "继续多部分加密或解密操作, 用来给解密或解密提供数据",
        "ENCRYPT": "加密",
        "DECRYPT": "解密",
        "ENCODE": "加密",
        "DECODE": "解密",
        "START_THREAD": "启动线程",
        "CREATE": "创建文件",
        "OPEN": "打开文件",
        "REMOVE": "删除文件",
        "WRITE": "写文件",
        "RENAME": "文件重命名",
        "MONITOR": "监控数据",
        "INSERT": "插入数据库",
        "DELETE": "删除数据库",
        "MODIFY": "修改数据库",
        "QUERY": "查询数据库",
        "PUT_STRING": "插入字符串",
        "PUT_STRINGSET": "插入字符集",
        "WIPEDATA": "擦除数据",
        "GET_IMEI": "获取IMEI",
        "GET_IMSI": "获取IMSI",
        "GET_SELF_NUMBER": "获取本机号码",
        "GET_CELL_LOCATION": "获取手机地址",
        "GET_NET_OPTNAME": "获取运营商名字",
        "GET_NET_OPT": "获取运营商",
        "GET_SIM_NUMBER": "获取sim卡号码",
        "LOC_UPDATES": "位置更新",
        "LOC_GET_LAST_KNOWN": "获取上次位置",
        "LOC_GET_LATITUDE": "获取纬度",
        "WIFI_ENABLE": "打开wifi",
        "WIFI_DISABLE": "关闭wifi",
        "AP_ENABLE": "启用AP",
        "AP_DISABLE": "禁用AP",
        "CALL": "打电话",
        "START_ACTIVITY": "启动activity",
        "WINDOW_GET_FOCUS": "获得焦点",
        "START_SERVICE": "启动线程",
        "BIND_SERVICE": "绑定服务",
        "EXEC": "执行系统命令",
        "KILL": "杀死进程",
        "KILL_QUIET": "安静杀死进程",
        "START": "启动进程",
        "INSTALL": "安装apk",
        "INIT_DEX_CLASSLOADER": "初始化DEX_CLASSLOADER",
        "INIT_PATH_CALSSLOADER": "初始化PATH_CALSSLOADER",
        "NOTIFY": "通知栏通知",
        "LOAD_LIB": "java层动态加载lib库",
        "TAKE_PHOTO": "照相",
        "START_TAKE_VIDEO": "开始录像",
        "START_RECORD_AUDIO": "开始录音",
        "STOP_RECORD_AUDIO": "停止录音",
        "MEDIA_CREATE": "创建媒体",
        "SEND": "发送",
        "RECEIVE": "接收",
        "GET_NETWORK_INFO": "获取网络信息",
        "EMULATOR_DETECTION": "模拟器对抗",
        "DLG_SHOW": "展示对话框",
        "DPM_ENABLE": "激活设备管理器",
        "DPM_DISABLE": "设备管理器收到ACTION_DEVICE_ADMIN_DISABLED广播",
        "DPM_IS_ADMIN_ACTIVE": "设备管理器是否激活",
        "HIDE_ICON": "隐藏图标",
        "SETPROPERTY": "设置属性",
        "CONSTRUCT": "hook UrlEncodedFormEntity类的构造器",
        "STAGEFRIGHT_DETECTOR": "检验STAGEFRIGHT",
        "SMS_INBOX_QUERY": "查询短信收件箱",
        "SMS_OUTBOX_QUERY": "查询短信发件箱",
        "SMS_DRAFT_QUERY": "查询短信草稿",
        "SMS_QUEUED_QUERY": "查询短信发送队列",
        "SMS_SENT_QUERY": "查询已发送的短信",
        "SMS_SEND_FAIL_QUERY": "查询发送失败的短信",
        "SMS_INBOX_INSERT": "插入短信收件箱",
        "SMS_OUTBOX_INSERT": "插入短信发件箱",
        "SMS_DRAFT_INSERT": "插入短信草稿",
        "SMS_QUEUE_INSERT": "插入短信发送队列",
        "SMS_SENT_INSERT": "插入已发送短信",
        "SMS_SEND_FAIL_INSERT": "插入发送失败短信",
        "SMS_INBOX_DELETE": "删除短信收件箱",
        "SMS_OUTBOX_DELETE": "删除短信发件箱",
        "SMS_DRAFT_DELETE": "删除短信草稿",
        "SMS_QUEUE_DELETE": "删除短信发送队列",
        "SMS_SENT_DELETE": "删除已发送短信",
        "SMS_PARSER": "解析短信内容",
        "SMS_SEND_FAIL_DELETE": "删除发送失败短信",
        "SMS_INBOX_MODIFY": "修改短信收件箱",
        "SMS_OUTBOX_MODIFY": "修改短信发件箱",
        "SMS_DRAFT_MODIFY": "修改短信草稿",
        "SMS_QUEUE_MODIFY": "修改短信发送队列",
        "SMS_SENT_MODIFY": "修改已发送短信",
        "SMS_SEND_FAIL_MODIFY": "修改发送失败短信",
        "CONTACT_DATA_QUERY": "查询联系人",
        "CONTACT_PHONE_QUERY": "查询联系人号码",
        "CONTACT_EMAILS_QUERY": "查询联系人邮箱",
        "CONTACT_POSTALS_QUERY": "查询联系人名片",
        "CONTACTS_QUERY": "查询联系人",
        "PEOPLE_QUERY": "查询联系人",
        "CONTACT_DATA_DELETE": "删除联系人",
        "CONTACT_PHONE_DELETE": "删除联系人号码",
        "CONTACT_EMAILS_DELETE": "删除联系人邮箱",
        "CONTACT_POSTALS_DELETE": "删除联系人名片",
        "CONTACTS_DELETE": "删除联系人",
        "PEOPLE_DELETE": "删除联系人",
        "CONTACT_DATA_INSERT": "添加联系人",
        "CONTACT_PHONE_INSERT": "添加联系人号码",
        "CONTACT_EMAILS_INSERT": "添加联系人邮箱",
        "CONTACT_POSTALS_INSERT": "添加联系人名片",
        "CONTACTS_INSERT": "添加联系人",
        "PEOPLE_INSERT": "添加联系人",
        "CONTACT_DATA_MODIFY": "修改联系人",
        "CONTACT_PHONE_MODIFY": "修改联系人号码",
        "CONTACT_EMAILS_MODIFY": "修改联系人邮箱",
        "CONTACT_POSTALS_MODIFY": "修改联系人名片",
        "CONTACTS_MODIFY": "修改联系人",
        "PEOPLE_MODIFY": "修改联系人",
        "CALLS": "打电话",
        "CREATE_SOCKET_CONNECT_AND_BIND": "创建sockey并且绑定和连接",
        "CREATE_SOCKET_ CONNECT": "创建sockey并且连接",
        "LOC_GET_LONGITUDE": "获取经度",
        "INSTALL_ADB": "安装adb",
        "UNINSTALL": "卸载apk",
        "RF_GET_METHOD": "通过反射获取方法",
        "RF_GET_CONSTRUCTOR": "通过反射获取构造方法",
        "RF_INVOKE": "通过反射调用方法",
        "VIEW_ACTION_SHOW": " （疑似弃用）",
        "VIEW_ACTION_ADD_FLOAT": "显示浮动窗口",
        "VIEW_ACTION_ADD_TO_TOP": "窗口置顶",
        "GET_INSTALLED_APP": "获取安装的app",
        "GET_INSTALLED_PKG": "获取安装的package",
        "DYNAMIC_BROADCAST": "动态广播",
        "STATIC_BROADCAST": "静态广播",
        "DPM_ACTIVITY_DISPLAY": "DeviceAdmin这个activity获得焦点",
        "SMS_INTERCEPT_BY": "短信拦截",
        "SHOW_TOAST": "显示提示信息",
        "SET_EMAIL_CONFIG": "发送邮件前设置邮件属性",
        "ENCODE_URL_PARAM": "对URL的参数进行编码",
        "DECODE_URL_PARAM": "对URL的参数进行解码",
        "NATIVE_LOAD_LIB": "native层动态加载lib库",
        "OPEN_DEVICE": "Native层打开/dev目录下文件",
        "OPEN_SYS": "Native层打开/sys目录下文件",
        "OPEN_PROC": "Native层打开/proc/目录下文件",
        "OPEN_SYSTEM": "Native层打开/system/目录下文件",
        "CREATE_SERVER_SOCKET": "创建serverSocket",
        "CREATE_LOCAL_SERVER_SOCKET": "创建本地serversocket",
        "NATIVE_SOCKET": "native层创建socket",
        "NATIVE_BIND": "native层bind",
        "NATIVE_CONNECT": "native层connect",
        "NATIVE_SOCKETPAIR": "native层socket_pair",
        "FIND_CLASS": "jni的查找类名函数",
        "GET_METHOD": "jni获得类方法",
        "GET_STATIC_METHOD": "获得静态方法",
        "CALL_VOID_METHOD": "jni调用java方法",
        "CALL_STATIC_OBJECT_METHOD": "调用静态方法",
        "CALL_OBJECT_METHOD": "调用对象方法",
        "CALL_NONVIRTUAL_VOID_METHOD": "调用非虚方法",
        "InboxSMS_SMS": "发送短信转发污点收件箱历史短信",
        "Contact_SMS": "发送短信转发污点联系人信息",
        "ReceivedSMS_SMS": "发送短信转发污点实时接收的短信",
        "PhoneRecord_SMS": "发送短信转发污点通话记录",
        "PhoneNum_SMS": "发送短信转发污点手机号码",
        "EnvironAudio_SMS": "发送短信泄露用户环境录音",
        "EnvironVideo_SMS": "发送短信泄露用户环境视频",
        "EnvironPhoto_SMS": "发送短信泄露用户环境照片",
        "GPSLocation_SMS": "发送短信泄露用户位置信息",
        "InboxSMS_Network": "网络上传污点收件箱历史短信",
        "Contact_Network": "网络上传污点联系人信息",
        "ReceivedSMS_Network": "网络上传污点实时接收的短信",
        "PhoneRecord_Network": "网络上传污点通话记录",
        "PhoneNum_Network": "网络上传污点手机号码",
        "EnvironAudio_Network": "网络上传用户环境录音",
        "EnvironVideo_Network": "网络上传用户环境视频",
        "EnvironPhoto_Network": "网络上传用户环境照片",
        "GPSLocation_Network": "网络上传用户位置信息",
        "InboxSMS_Email": "发送邮件上传污点收件箱历史短信",
        "Contact_Email": "发送邮件上传污点联系人信息",
        "ReceivedSMS_Email": "发送邮件上传污点实时接收的短信",
        "PhoneRecord_Email": "发送邮件上传污点通话记录",
        "PhoneNum_Email": "发送邮件上传污点手机号码",
        "EnvironAudio_Email": "发送邮件上传用户环境录音",
        "EnvironVideo_Email": "发送邮件上传用户环境视频",
        "EnvironPhoto_Email": "发送邮件上传用户环境照片",
        "GPSLocation_Email": "发送邮件上传用户位置信息",
        "Contact_SMSSendTo": "向污点联系人发送短信",
        "SenFile_Download": "特定文件类型下载",
        "SMS_Send": "滥用短信功能进行静默发送短信",
        "MMS_Send": "滥用彩信功能进行静默发送彩信",
        "DPM_Enable": "激活设备管理器",
        "Maybe_Window": "疑似顶层窗口劫持",
        "TopActivity_Window": "顶层窗体劫持",
        "PhoneAccount_SMS": "短信泄露电话号码",
        "QQ_SMS": "短信泄露qq号和密码",
        "Alipay_SMS": "短信泄露支付宝账号和密码",
        "Wechat_SMS": "短信泄露微信账号和密码",
        "Taobao_SMS": "短信泄露淘宝账号和密码",
        "BankAccount_SMS": "短信泄露银行账号",
        "PhoneAccount_Network": "网络上传钓鱼手机号码",
        "QQ_Network": "网络上传污点qq号和密码",
        "Alipay_Network": "网络上传污点支付宝账号和密码",
        "Wechat_Network": "网络上传污点微信账号和密码",
        "Taobao_Network": "网络上传污点淘宝账号和密码",
        "BankAccount_Network": "网络上传污点银行账号",
        "PhoneAccount_Email": "邮件上传污点电话号码",
        "QQ_Email": "邮件上传污点qq号和密码",
        "Alipay_Email": "邮件上传污点支付宝账号",
        "Wechat_Email": "邮件上传污点微信账号和密码",
        "Taobao_Email": "邮件上传污点淘宝账号和密码",
        "BankAccount_Email": "邮件上传污点银行账号",
        "Icon": "隐藏图标",
        "Install": "静默安装",
        "TopWindow_Lock": "窗口置顶",
        "FloatWindow_Lock": "悬浮窗体",
        "Document_Enc": "文件加密",
        "Document_Def": "文件压缩",
        "Notify_Show": "频繁弹出通知栏",
        "FloatWindow_Show": "频繁弹出浮动窗口",
        "Icon_Create": "频繁创建图标",
        "Malware": "包含恶意代码",
        "Tool": "包含其他工具",
        "Downloader": "下载其他恶意代码",
        "Adware_SMS": "通过短信推广广告",
        "Payware_SMS": "通过短信推广支付件",
        "Malware_SMS": "通过短信推广病毒",
        "ReceiveMMS_Network": "通过网络上传污点实时接收的彩信",
        "InboxMMS_Network": "通过网络上传污点收件箱历史彩信",
        "InternetRecords_Network": "通过网络上传污点上网记录",
        "PhoneAudio_Network": "通过网络上传通话录音",
        "LocalAudio_Network": "通过网络上传本地音频",
        "LocalVideo_Network": "通过网络上传本地视频",
        "LocalPhoto_Network": "通过网络上传本地图片",
        "LocalFile_Network": "通过网络上传本地文件",
        "ReceiveMMS_Email": "通过邮件上传污点实时接收的彩信",
        "InboxMMS_Email": "通过邮件上传污点收件箱历史彩信",
        "InternetRecords_Email": "通过邮件上传污点上网记录",
        "PhoneAudio_Email": "通过邮件上传通话录音",
        "LocalAudio_Email": "通过邮件上传本地音频 ",
        "LocalVideo_Email": "通过邮件上传本地视频",
        "LocalPhoto_Email": "通过邮件上传本地图片",
        "LocalFile_Email": "通过邮件上传本地文件",
        "InternetRecords_SMS": "通过短信上传污点上网记录",
        "Contact_MMSSendTo": "向污点联系人发送彩信",
        "Bluetooth": "开启蓝牙",
        "NFC": "开启NFC",
        "Screenshot": "后台截屏",
        "Email_Send": "滥用邮件功能发送邮件",
        "SMS_Intercept_By": "滥用短信拦截功能",
        "PhoneCall": "滥用拨打电话功能拨打电话",
        "EnvironPhoto": "滥用拍照功能拍摄照片",
        "EnvironVideo": "滥用摄像功能拍摄视频",
        "EnvironAudio": "滥用录音功能进行录音",
        "Network": "频繁链接网络",
        "TEL_PHONESTATE_LISTEN": "监听来电状态",
        "SCREEN_BITMAP": "后台截屏",
        "SCREEN_GRAPHICS": "后台截屏",
        "SCREEN_SCREENCAP": "后台截屏",
        "GET_BLUETOOTH": "获取蓝牙适配器",
        "OPEN_BLUETOOTH": "开启蓝牙",
        "CLOSE_BLUETOOTH": "关闭蓝牙",
        "GET_ADDRESS": "获取本地蓝牙地址",
        "GET_NFC": "获取NFC适配器",
        "ISENABLE_NFC": "NFC是否可用",
        "START_DISPATCH_NFC": "开始调度NFC",
        "STOP_DISPATCH_NFC": "停止调度NFC",
        "BROWSER_QUERY": "查询浏览器历史记录/书签",
        "BROWSER_MODIFY": "修改浏览器历史记录/书签",
        "BROWSER_INSERT": "插入浏览器历史记录/书签",
        "BROWSER_DELETE": "删除浏览器历史记录/书签",
        "CALENDAR_QUERY": "查询日程表历史记录  ",
        "CALENDAR_MODIFY": "修改日程表历史记录",
        "CALENDAR_INSERT": "插入日程表历史记录",
        "CALENDAR_DELETE": "删除日程表历史记录",
        "GET_CLIENT_SSL_SOCKET": "获取 SSL Socket",
        "GET_SERVER_SSL_SOCKET": "获取 SSL ServerSocket",
        "GET_SSL_INPUTSTREAM": "获取 SSL 输入流",
        "CHECK_SSL_SERVER_TRUSTED": "检查服务器证书是否信任",
        "CREATE_SSL_SOCKET": "创建 SSL Socket",
        "STARTWATCHING": "启动监听文件或文件目录",
        "STOPWATCHING": "停止监听文件或文件目录",
        "ACCESS": "文件被访问",
        "ATTRIB": "属性被修改",
        "CLOSE_WRITE": "可写文件被close",
        "MOVED_FROM": "文件被移走",
        "MOVED_TO": "文件被移来",
        "DELETE_SELF": "自删除",
        "MOVE_SELF": "自移动",
        "CLOSE": "文件被关闭",
        "name": "行为",
        "time": "时间",
        "upl": "隐私上传",
        "flo": "流量消耗",
        "bev": "行为规则",
        "SMS_MONITOR": "短信监控",
        "LIST_FILES": "查看文件列表",
        "CONNECT": "连接指定地址",
        "LIST_FILES": "列出目录下文件",
        "NO_ICON": "无图标",
        "PM_INFO": "获取应用程序名",
        "GET_SIM_OPT": "获取SIM卡运行商",
        "GET_SIM_OPTNAME": "获取SIM卡运行商名称",
        "COMPRESS": "压缩",
        "DECOMPRESS": "解压缩",
        "GET_ALL_ENTRY": "获取压缩包内全部文件",
        "GET_ONE_ENTRY": "获取压缩包中一个文件名",
        "KILLPROCESS": "杀死进程",
        "VIEW_SETTEXT": "设置窗口字符串",
        "CLICK_BUTTON": "点击按钮",
        "GET_KEY_INSTANCE": "获取密钥生成器",
        "GET_RUNNING_TASK": "获取正在运行任务",
        "SHORTCUT_INSTALL": "安装快捷图标",
        "SHOIRTCUT_UNINSTALL": "卸载快捷图标"
    };
    return translation;
}

export function high_danger_word() {
    var high = new Array("WIPEDATA", "DPM_IS_ADMIN_ACTIVE", "HIDE_ICON", "EMULATOR_DETECTION",
        "SMS_INBOX_INSERT", "SMS_OUTBOX_INSERT", "SMS_DRAFT_INSERT", "SMS_QUEUE_INSERT", "SMS_SENT_INSERT",
        "SMS_SEND_FAIL_INSERT", "SMS_INSERT", "SMS_INBOX_DELETE", "SMS_OUTBOX_DELETE", "SMS_DRAFT_DELETE",
        "SMS_QUEUE_DELETE", "SMS_SENT_DELETE", "SMS_SEND_FAIL_DELETE", "SMS_DELETE", "SMS_INBOX_MODIFY",
        "SMS_OUTBOX_MODIFY", "SMS_DRAFT_MODIFY", "SMS_QUEUE_MODIFY", "SMS_SENT_MODIFY",
        "SMS_SEND_FAIL_MODIFY", "SMS_MODIFY", "SMS_SEND", "SMS_INTERCEPT_BY", "CONTACT_DATA_DELETE",
        "CONTACT_PHONE_DELETE", "CONTACT_EMAILS_DELETE", "CONTACT_POSTALS_DELETE", "CONTACTS_DELETE",
        "PEOPLE_DELETE", "CONTACT_DATA_INSERT", "CONTACT_PHONE_INSERT", "CONTACT_EMAILS_INSERT",
        "CONTACT_POSTALS_INSERT", "CONTACTS_INSERT", "PEOPLE_INSERT", "CONTACT_DATA_MODIFY",
        "CONTACT_PHONE_MODIFY", "CONTACT_EMAILS_MODIFY", "CONTACT_POSTALS_MODIFY", "CONTACTS_MODIFY",
        "PEOPLE_MODIFY", "CALLS_ADD", "CALLS_DEL", "CALLS_MODIFY", "CALLS_QUERY", "TAKE_PHOTO", "START_RECORD_AUDIO",
        "STOP_RECORD_AUDIO", "START_TAKE_VIDEO", "INSTALL", "INSTALL_ADB", "UNINSTALL", "CALL", "STAGEFRIGHT_DETECTOR",
        "OPEN_DEVICE", "OPEN_SYS", "OPEN_PROC", "OPEN_SYSTEM", "DPM_ENABLE", "PhoneCall", "OPEN_BLUETOOTH",
        "CLOSE_BLUETOOTH", "GET_ADDRESS", "START_DISPATCH_NFC", "STOP_DISPATCH_NFC", "MMS_SEND");
    return high;
}

export function middle_danger_word() {
    var middle = new Array("NOTIFY", "VIEW_ACTION_ADD_TO_TOP", "SMS_INBOX_QUERY", "SMS_OUTBOX_QUERY",
        "SMS_DRAFT_QUERY", "SMS_QUEUED_QUERY", "SMS_SENT_QUERY", "SMS_SEND_FAIL_QUERY", "SMS_QUERY",
        "SMS_RECEIVE", "SMS_PARSER", "CONTACT_DATA_QUERY", "CONTACT_PHONE_QUERY", "CONTACT_EMAILS_QUERY",
        "CONTACT_POSTALS_QUERY", "CONTACTS_QUERY", "PEOPLE_QUERY", "MEDIA_CREATE", "AP_ENABLE", "AP_DISABLE",
        "WIFI_ENABLE", "WIFI_DISABLE", "GET_CELL_LOCATION", "GET_NET_OPTNAME", "GET_NET_OPT", "GET_SIM_NUMBER",
        "LOC_UPDATES", "LOC_GET_LAST_KNOWN", "LOC_GET_LONGITUDE", "LOC_GET_LATITUDE", "GET_INSTALLED_APP",
        "GET_INSTALLED_PKG", "AUTO_BOOT", "SHUTDOWN", "TEL_PHONESTATE_LISTEN", "SCREEN_BITMAP", "SCREEN_GRAPHICS",
        "SCREEN_SCREENCAP", "GET_BLUETOOTH", "GET_NFC", "ISENABLE_NFC", "BROWSER_QUERY", "BROWSER_MODIFY",
        "BROWSER_INSERT", "BROWSER_DELETE", "CALENDAR_QUERY", "CALENDAR_MODIFY", "CALENDAR_INSERT", "CALENDAR_DELETE");
    return middle;
}

export function state() {
    var state = {
        "-1": "程序已经存在（重复养殖后完成）",
        "-2": "模拟器空间不足",
        "-3": "无效apk",
        "-4": "样本安装超时",
        "-5": "SD卡访问失败",
        "-6": "没有证书",
        "-7": "样本不存在或无效的安装路径",
        "-8": "SD卡不存在、不可用",
        "-9": "minSdkVersion版本不支持",
        "-10": "avml文件不存在或系统问题导致安装失败",
        "-11": "样本反复养殖3次仍然失败",
        "-12": "AVML和Pcap文件上传失败",
        "-13": "AVML上传失败",
        "-14": "Pcap上传失败",
        "-15": "样本养殖卡死",
        "-16": "USB连接断开",
        "-17": "手机型号不匹配",
        "-9999": "样本安装失败，未知原因",
        "3": "动态系统投放失败",
        "7": "动态分析超时"
    };
    return state;
}

export function state_engine() {
    var state_engine = {
        "3": "结果文件转换失败",
        "5": "删除结果文件失败",
        "6": "状态更新失败",
        "7": "分析超时",
        "10": "扫描结果文件不存在",
    };
    return state_engine;
}

export function state_ratcher() {
    var state_ratcher = {
        "3": "扫描结果存储异常",
        "4": "漏洞模块执行失败",
        "7": "分析超时",
    };
    return state_ratcher;
}

export function scenType () {
  var scenType = {
    'Steal': '窃取隐私(Steal)',
    'Abuse': '功能滥用(Abuse)',
    'Hijack': '监听劫持(Hijack)',
    'Hide': '隐藏类(Hide)',
    'Ransom': '勒索技术类(Ransom)',
    'Encrypt': '加密类(Encrypt)',
    'Deflate': '压缩类(Deflate)',
    'Flood': '洪范式攻击类(Flood)',
    'Payload': '银弹类(Payload)',
    'Spread': '传播类(SprTead)'
  }
  return scenType
}

export function netType () {
  var netType = {
    'srcport': '源端口',
    'destport': '目的端口'
  }
  return netType
}

export function permission () {
  var permission = {
    "ACCESS_CHECKIN_PROPERTIES":"访问登记属性",
    "ACCESS_COARSE_LOCATION":"获取错略位置",
    "ACCESS_FINE_LOCATION":"获取精确位置",
    "ACCESS_LOCATION_EXTRA_COMMANDS":"访问定位额外命令",
    "ACCESS_NETWORK_STATE":"获取网络状态",
    "ACCESS_MOCK_LOCATION":"获取模拟定位信息",
    "ACCESS_WIFI_STATE":"获取WiFi状态",
    "ACCOUNT_MANAGER":"账户管理",
    "ADD_VOICEMAIL":"添加语音邮件",
    "ANSWER_PHONE_CALLS":"允许接听电话",
    "BATTERY_STATS":"电量统计",
    "BIND_ACCESSIBILITY_SERVICE":"绑定Accessibility",
    "BIND_APPWIDGET":"绑定小插件",
    "BIND_AUTOFILL_SERVICE":"绑定Autofill",
    "BIND_CARRIER_SERVICES":"绑定服务运营商",
    "BIND_CHOOSER_TARGET_SERVICE":"绑定chooserTarget",
    "BIND_CONDITION_PROVIDER_SERVICE":"绑定ConditionProvider",
    "BIND_DEVICE_ADMIN":"绑定设备管理",
    "BIND_DREAM_SERVICE":"绑定Dream服务",
    "BIND_INCALL_SERVICE":"绑定Incall",
    "BIND_INPUT_METHOD":"绑定输入法",
    "BIND_MIDI_DEVICE_SERVICE":"绑定Midi设备",
    "BIND_NFC_SERVICE":"绑定NFC",
    "BIND_NOTIFICATION_LISTENER_SERVICE":"绑定系统监听",
    "BIND_PRINT_SERVICE":"绑定打印",
    "BIND_QUICK_SETTINGS_TILE":"绑定快速设定",
    "BIND_REMOTEVIEWS":"绑定RemoteView",
    "BIND_SCREENING_SERVICE":"绑定来电过滤",
    "BIND_TELECOM_CONNECTION_SERVICE":"绑定通信连接",
    "BIND_TEXT_SERVICE":"绑定文字服务",
    "BIND_TV_INPUT":"绑定TV输入",
    "BIND_VISUAL_VOICEMAIL_SERVICE":"绑定虚拟语音邮件",
    "BIND_VOICE_INTERACTION":"绑定VoiceInteraction",
    "BIND_VPN_SERVICE":"绑定VPN",
    "BIND_VR_LISTENER_SERVICE":"绑定VR监听",
    "BIND_WALLPAPER":"绑定壁纸",
    "BLUETOOTH":"使用蓝牙",
    "BLUETOOTH_ADMIN":"蓝牙管理",
    "BLUETOOTH_PRIVILEGED":"允许蓝牙配对",
    "BROADCAST_PACKAGE_REMOVED":"应用删除时广播",
    "BROADCAST_SMS":"收到短信时广播",
    "BROADCAST_STICKY":"连续广播",
    "BROADCAST_WAP_PUSH":"WAP PUSH广播",
    "CALL_PHONE":"拨打电话",
    "CALL_PRIVILEGED":"通话权限",
    "CAMERA":"拍照权限",
    "CAPTURE_AUDIO_OUTPUT":"捕捉音频输出",
    "CAPTURE_SECURE_VIDEO_OUTPUT":"捕捉安全视频输出",
    "CAPTURE_VIDEO_OUTPUT":"捕捉视频输出",
    "CHANGE_COMPONENT_ENABLED_STATE":"改变组件状态",
    "CHANGE_CONFIGURATION":"改变配置",
    "CHANGE_NETWORK_STATE":"改变网络状态",
    "CHANGE_WIFI_MULTICAST_STATE":"改变WiFi多播状态",
    "CHANGE_WIFI_STATE":"改变WiFi状态",
    "CLEAR_APP_CACHE":"清除应用缓存",
    "CONTROL_LOCATION_UPDATES":"控制定位更新",
    "DELETE_CACHE_FILES":"删除缓存文件",
    "DELETE_PACKAGES":"删除应用",
    "DIAGNOSTIC":"应用诊断",
    "DISABLE_KEYGUARD":"禁用键盘锁",
    "DUMP":"转存系统信息",
    "EXPAND_STATUS_BAR":"状态栏控制",
    "FACTORY_TEST":"工厂测试模式",
    "GET_ACCOUNTS":"问账户Gmail列表",
    "GET_ACCOUNTS_PRIVILEGED":"允许访问账户列表",
    "GET_PACKAGE_SIZE":"获取应用大小",
    "GET_TASKS":"获取任务信息",
    "GLOBAL_SEARCH":"允许全局搜索",
    "INSTALL_LOCATION_PROVIDER":"安装定位提供",
    "INSTALL_PACKAGES":"安装应用程序",
    "INSTALL_SHORTCUT":"安装快捷方式",
    "INTERNET":"访问网络",
    "KILL_BACKGROUND_PROCESSES":"结束后台进程",
    "MANAGE_DOCUMENTS":"文件管理",
    "MASTER_CLEAR":"软格式化",
    "MEDIA_CONTENT_CONTROL":"多媒体内容控制",
    "MODIFY_AUDIO_SETTINGS":"修改声音设置",
    "MODIFY_PHONE_STATE":"修改电话状态",
    "MOUNT_FORMAT_FILESYSTEMS":"格式化文件系统",
    "MOUNT_UNMOUNT_FILESYSTEMS":"挂载文件系统",
    "NFC":"允许NFC通讯",
    "PACKAGE_USAGE_STATS":"应用统计信息",
    "PERSISTENT_ACTIVITY":"永久Activity",
    "PROCESS_OUTGOING_CALLS":"处理拨出电话",
    "READ_CALENDAR":"读取日程提醒",
    "READ_CALL_LOG":"读取来电记录",
    "READ_CONTACTS":"读取联系人",
    "READ_EXTERNAL_STORAGE":"读取外部存储",
    "READ_FRAME_BUFFER":"屏幕截图",
    "READ_INPUT_STATE":"读取输入状态",
    "READ_LOGS":"读取系统日志",
    "READ_PHONE_NUMBERS":"读取电话号码",
    "READ_PHONE_STATE":"读取电话状态",
    "READ_SMS":"读取短信内容",
    "READ_SYNC_SETTINGS":"读取同步设置",
    "READ_SYNC_STATS":"读取同步状态",
    "READ_VOICEMAIL":"读取语音邮件",
    "REBOOT":"重启设备",
    "RECEIVE_BOOT_COMPLETED":"开机自动允许",
    "RECEIVE_MMS":"接收彩信",
    "RECEIVE_SMS":"接收短信",
    "RECEIVE_WAP_PUSH":"接收Wap Push",
    "RECORD_AUDIO":"录音",
    "REORDER_TASKS":"排序系统任务",
    "REQUEST_COMPANION_RUN_IN_BACKGROUND":"请求允许同伴应用后台运行",
    "REQUEST_COMPANION_USE_DATA_IN_BACKGROUND":"请求运行后台读取同伴用户信息",
    "REQUEST_DELETE_PACKAGES":"请求允许删除应用文件",
    "REQUEST_IGNORE_BATTERY_OPTIMIZATIONS":"请求加入白名单",
    "REQUEST_INSTALL_PACKAGES":"请求允许安装应用",
    "RESTART_PACKAGES":"结束系统任务",
    "SEND_RESPOND_VIA_MESSAGE":"",
    "SEND_SMS":"发送短信",
    "WRITE_SMS":"写入短信",
    "SET_ALARM":"设置闹铃提醒",
    "SET_ALWAYS_FINISH":"设置总是退出",
    "SET_ANIMATION_SCALE":"设置动画缩放",
    "SET_DEBUG_APP":"设置调试程序",
    "SET_PREFERRED_APPLICATIONS":"设置应用参数",
    "SET_PROCESS_LIMIT":"设置进程限制",
    "SET_TIME":"设置系统时间",
    "SET_TIME_ZONE":"设置系统时区",
    "SET_WALLPAPER":"设置桌面壁纸",
    "SET_WALLPAPER_HINTS":"设置壁纸建议",
    "SIGNAL_PERSISTENT_PROCESSES":"发送永久进程信号",
    "STATUS_BAR":"状态栏控制",
    "SYSTEM_ALERT_WINDOW":"显示系统窗口",
    "TRANSMIT_IR":"允许使用红外发射器",
    "UNINSTALL_SHORTCUT":"删除快捷方式",
    "UPDATE_DEVICE_STATS":"更新设备状态",
    "USE_FINGERPRINT":"使用指纹",
    "USE_SIP":"使用SIP视频",
    "VIBRATE":"允许震动",
    "WAKE_LOCK":"唤醒锁定",
    "WRITE_APN_SETTINGS":"写入GPRS接入点设置",
    "WRITE_CALENDAR":"写入日程提醒",
    "WRITE_CALL_LOG":"写入通话记录",
    "WRITE_CONTACTS":"写入通讯录",
    "WRITE_EXTERNAL_STORAGE":"写入外部存储",
    "WRITE_GSERVICES":"写入google地图数据",
    "WRITE_SECURE_SETTINGS":"写入系统敏感设置",
    "WRITE_SETTINGS":"写入系统设置",
    "WRITE_SYNC_SETTINGS":"写入在线同步设置",
    "WRITE_VOICEMAIL":"写入语音邮件",
    "BROADCAST_PACKAGE_ADDED":"自定义权限：应用添加时广播",
    "BROADCAST_PACKAGE_CHANGED":"自定义权限：应用改变时广播",
    "BROADCAST_PACKAGE_INSTALL":"自定义权限：应用安装时广播",
    "BROADCAST_PACKAGE_REPLACED":"自定义权限：应用替换时广播",
    "MANAGE_ACCOUNTS":"管理账户",
    "AUTHENTICATE_ACCOUNTS":"验证账户",
    "USE_CREDENTIALS":"使用证书",
    "READ_SETTINGS":"读取设置信息",
    "FLASHLIGHT":"使用闪关灯",
    "ACCESS_SUPERUSER":"获取超级用户权限",
    "BIND_ACCESSIBILITY_SERVICE":"自定义权限",
    "MIPUSH_RECEIVE":"自定义权限：接收小米推送消息",
    "ACCESS_MTK_MMHW":"自定义权限",
    "PERSISTENT_ACTIVITY":"永久Activity"
  }
  return permission
}

export function securityflawsType () {
  var securityflawsType = {
    "明文数字证书风险": "应用数据安全",
    "共享变量存储安全": "应用数据安全",
    "data目录读写数据库权限": "应用数据安全",
    "data目录文件读写权限": "应用数据安全",
    "剪切板信息安全风险": "应用数据安全",
    "Activity组件暴露风险": "组件安全",
    "Service组件暴露风险": "组件安全",
    "Receiver组件暴露风险": "组件安全",
    "ContentProvider暴露风险": "组件安全",
    "声明组件不存在风险": "组件安全",
    "权限过剩": "权限安全",
    "权限不足": "权限安全",
    "自定义权限安全等级过低": "权限安全",
    "允许备份allowBackup风险": "权限安全",
    "允许调试debuggable风险": "权限安全",
    "使用不安全的加密模式": "加密算法安全",
    "加密过程使用伪随机数": "加密算法安全",
    "Webview隐藏接口漏洞（CVE-2014-1939）": "本地接口安全",
    "Webview组件远程代码执行漏洞": "本地接口安全",
  }
  return securityflawsType
}

export function securityflawsRisk () {
  var securityflawsRisk = {
    "明文数字证书风险": "中危",
    "共享变量存储安全": "中危",
    "data目录读写数据库权限": "中危",
    "data目录文件读写权限": "中危",
    "剪切板信息安全风险": "中危",
    "Activity组件暴露风险": "高危",
    "Service组件暴露风险": "高危",
    "Receiver组件暴露风险": "中危",
    "ContentProvider暴露风险": "中危",
    "声明组件不存在风险": "中危",
    "权限过剩": "低危",
    "权限不足": "中危",
    "自定义权限安全等级过低": "中危",
    "允许备份allowBackup风险": "中危",
    "允许调试debuggable风险": "高危",
    "使用不安全的加密模式": "中危",
    "加密过程使用伪随机数": "中危",
    "Webview隐藏接口漏洞（CVE-2014-1939）": "中危",
    "Webview组件远程代码执行漏洞": "高危",
  }
  return securityflawsRisk
}